### ISSUE TITLE
Failed to create PkiRootCA SYSVOL folder

### ISSUE THREAD

**Issue by skolenkin** [aws-quickstart/quickstart-microsoft-pki#34]
Hi,
Deploying 2 tier CA template with AWS Managed AD always fails with error message below:

```
Creating PkiSysvolPSDrive
Creating the PkiRootCA SYSVOL folder
Failed to create PkiRootCA SYSVOL folder Access to the path 'PkiRootCA' is denied.
```

I have tested configuration with S3 bucket and without S3 bucket.

My Environment:
1 - AWS Directory Service (Managed AD Standard edition) 
2 - 2 Private subnets 
3 - NAT GW to allow the instances to download packages and software.

This is link to [cloudformation template](https://aws-quickstart.s3.amazonaws.com/quickstart-microsoft-pki/templates/microsoft-pki.template.yaml)
Also, I used steps from the following [aws documentation](https://aws.amazon.com/blogs/security/how-to-enable-ldaps-for-your-aws-microsoft-ad-directory/)

**Comment by girvenj** [comment]
Did you select the correct DirectoryType?  If you are using Managed AD make sure select "AWSManaged"

**Comment by skolenkin** [comment]
@girvenj  I used the following parameters:

AMI: /aws/service/ami-windows-latest/Windows_Server-2019-English-Full-Base
AdministratorSecret: arn:aws:secretsmanager:us-east-1:...
CADeploymentType: Two-Tier
CaHashAlgorithm: SHA256
CaKeyLength: 2048
CaServerSubnet: subnet-...
CaValidityPeriodUnits: 5
DirectoryType: AWSManaged
DomainController1IP: IP1
DomainController2IP: IP2
DomainDNSName: awsad.test
DomainMembersSG: sg-...
DomainNetBIOSName: awsad
EntCaDataDriveSizeGiB: 2
EntCaServerInstanceType: t3.medium
EntCaServerNetBIOSName: ENTCA1
KeyPairName: KEY
OrCaDataDriveSizeGiB: 2
OrCaServerInstanceType: t3.medium
OrCaServerNetBIOSName: ORCA1
OrCaValidityPeriodUnits: 10
QSS3BucketName: aws-quickstart
QSS3BucketRegion: us-east-1
QSS3KeyPrefix: quickstart-microsoft-pki/
S3CRLBucketName: BUCKET
UseS3ForCRL: No
VPCCIDR: CIDR
VPCID: VPCID

**Comment by girvenj** [comment]
Also, what permissions do the credentials you have in the AdministratorSecret have?

**Comment by skolenkin** [comment]
We created new user (in this case CAAdmin) in our AWS Managed AD and added this user to the AWS Delegated Enterprise Certificate Authority Administrators security group.
We used steps from  the following link:
https://aws.amazon.com/blogs/security/how-to-enable-ldaps-for-your-aws-microsoft-ad-directory/

**Comment by girvenj** [comment]
Since we are using the SYSVOL, also add that user to the "AWS Delegated Group Policy Administrators" group.  I need to update the blog to include that.  We are creating a folder in the SYSVOL, so the CAs can pass the certs and request to each other.

**Comment by skolenkin** [comment]
@girvenj Thank you very much 
I will try.

**Comment by girvenj** [comment]
Actually that will fail as well.  You need to add the user to the "AWS Delegated Administrators" group not the "AWS Delegated Group Policy Administrators" group.

**Comment by skolenkin** [comment]
I added these permissions but I have got the error:
```
Failed to create PkiSysvolPSDrive The specified network password is not correct
```

**Comment by girvenj** [comment]
That sounds like you secret PW is out is sync with AD  or the Secret is not formatted correctly.  The key names have to be "username" and "password".   Just tested and I was able to successfully launch it. 

If you get it it should look like:

C:\WINDOWS\system32> Get-SECSecretValue arn:aws:secretsmanager:us-west-2:############:secret:DefaultCreds-Example

ARN           : arn:aws:secretsmanager:us-west-2:############:secret:DefaultCreds-Example
CreatedDate   : 
Name          : DefaultCreds
SecretBinary  :
SecretString  : {"username":"CAAdmin","password":"P@ssw0rd"}
VersionId     : 
VersionStages : {AWSCURRENT}

**Comment by skolenkin** [comment]
@girvenj 
I was able to create a Cloudformation stack after a changed the password from Password123! to P@ssw0rd.
But password Password123! works fine for logging into Windows.

Thank you very much
