### ISSUE TITLE
Hardcoded AMI images are not available anymore in eu-central-1

### ISSUE THREAD

**Issue by mkuendig** [aws-quickstart/quickstart-microsoft-pki#58]
Get an error that the AMI is not available anymore in eu-central-1

The same cfn still worked on Monday. Seems the AMI referenced/hardcoded can't be used anymore.

**Comment by ArthurKnoep** [comment]
The same happens in us-east-1 too, I'm guessing that all regions are impacted
This is the error event I got from the cloudformation console
![image](https://user-images.githubusercontent.com/27413532/190652669-a8666edd-8828-4f22-9b2a-51890260ebf7.png)

Digging a bit in the template and it seems that it's targeting an AMI version from may 2022
https://github.com/aws-quickstart/quickstart-microsoft-pki/blob/main/templates/two-tier.template#L333

This AMI is four version old and AWS only seems to keep the last 3 ones active(https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ec2-windows-ami-version-history.html)

**Comment by ArthurKnoep** [comment]
I'm doing the exact same thing at the moment :laughing:

**Comment by fjleon1980** [comment]
I just noticed this today. I have reported this to AWS directly. your current solution is the only workaround at this time

**Comment by fjleon1980** [comment]
AWS just fixed this issue in https://github.com/aws-quickstart/quickstart-microsoft-pki/pull/59

**Comment by davmayd** [comment]
Change was introduced by https://github.com/aws-quickstart/quickstart-microsoft-pki/pull/55 due to an issue with a June Windows update, and was reverted by https://github.com/aws-quickstart/quickstart-microsoft-pki/pull/59.
