### ISSUE TITLE
Templates do not exist

### ISSUE THREAD

**Issue by cornickj** [aws-quickstart/quickstart-microsoft-pki#67]
Receive an error when trying to deploy in us-east-1:
S3 error: Access Denied For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

Tried downloading the template and get a similar error:
```
❯ aws s3 cp s3://aws-ia-us-east-1.s3.us-east-1.amazonaws.com/cfn-ps-microsoft-pki/templates/two-tier.template .
fatal error: An error occurred (404) when calling the HeadObject operation: Key "cfn-ps-microsoft-pki/templates/two-tier.template" does not exist
```

It looks like permissions on that bucket may have an issue?

**Comment by cornickj** [comment]
Worked around by downloading the templates from here and uploading to my own bucket in the same paths, but it definitely adds friction for people following the directions at https://aws-quickstart.github.io/quickstart-microsoft-pki/#_deployment_options

**Comment by vsnyc** [comment]
@cornickj - thanks for reporting this. Assuming you started the deployment from here: https://aws.amazon.com/solutions/implementations/microsoft-pki/, this should be fixed. Note that we are in the process of migrating repos to another org. The new repo is: https://github.com/aws-ia/cfn-ps-microsoft-pki/. 

I had updated the deployment links yesterday and realized to update the nested `quickstart-` in CloudFormation quickcreate links. The [Deploy into an existing VPC](https://fwd.aws/vgDqv) link should have worked, but I've now update the [Deploy into a new VPC](https://fwd.aws/V4P9Q) link as well.
